### ISSUE TITLE
Career Details Page

### ISSUE THREAD

**Issue by spykelionel** [skye8-tech/givest#38]
# Issue Summary

There's a career's page, but we need a career's details page. This page seems to be missing in the design, so you might want to be creative here.

**Comment by N-TITIAN** [comment]
here is the proposed design @spykelionel  
https://www.figma.com/design/QXV8TCzTjo4cWcGPDczIZT/Chiarityshay-(Community)-(Copy)?node-id=2802-415&t=xqVYIsX0mBTppPkb-1

Clicking a career card should open this then "apply now " can open form

**Comment by spykelionel** [comment]
@Minetbayeka here
